spring.application.name=dux-spring-boot-starter
spring.datasource.url=jdbc:sqlite:file:C:/Users/karan/Projects/dux4j/spring-boot-starter/src/main/resources/bookstore.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON
